// resources/js/Pages/Welcome.jsx
import { Link, Head } from '@inertiajs/react';
import MainCarousel from './Main/MainCarousel';  // Adjust the path if necessary

export default function Welcome({ auth }) {
    return (
        <>
            <Head title="Nove" />

            <div className="container-fluid" dir="rtl">

                <div className="login-register m-3">
                    {auth.user ? (
                        <Link href={route('dashboard')} className="btn-link">
                            Dashboard
                        </Link>
                    ) : (
                        <>
                            <Link href={route('login')} className="btn-link">
                                تسجيل الدخول
                            </Link>
                            <Link href={route('register')} className="btn-link ml-4">
                                إشتراك
                            </Link>
                        </>
                    )}
                </div>

                <nav className="navbar navbar-expand-lg m-2">
                    <div className="container-fluid">
                        <a className="navbar-brand" href="#">
                            <img src="/images/logo-brand.png" alt="شعار المتجر" className="logo-brand" />
                        </a>
                        <button
                            className="navbar-toggler"
                            type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#navbarNav"
                            aria-controls="navbarNav"
                            aria-expanded="false"
                            aria-label="Toggle navigation"
                        >
                            <span className="navbar-toggler-icon"></span>
                        </button>
                        <div className="collapse navbar-collapse" id="navbarNav">
                            <ul className="navbar-nav ml-auto">
                                <li className="nav-item">
                                    <a className="nav-link" href="#">الرئيسية</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link" href="#">المنتجات</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link" href="#">العلامات التجارية</a>
                                </li>
                                <li className="nav-item">
                                    <a className="nav-link" href="#">التصنيفات</a>
                                </li>
                            </ul>
                        </div>
                        <div className="login-search">
                            <div className="search-bar">
                                <input type="text" placeholder="ابحث عن منتجات..." className="form-control" />
                                <button className="btn btn-primary">بحث</button>
                            </div>
                        </div>
                    </div>
                </nav>

                <div className="main-container">
                    <div className="brands-section">
                        <div className="container">

                        </div>
                    </div>
                    <div className="categories-section">
                        <div className="container">
                        <MainCarousel />
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

// resources/js/Pages/Welcome.vue

<template>
  <div class="container-fluid" :dir="rtl">

    <!-- شريط علوي -->
    <div class="login-register m-3">
      <a href="#">تسجيل الدخول</a>
      <span class="divider">|</span>
      <a href="#">الاشتراك</a>
    </div>
    <nav class="navbar navbar-expand-lg m-2">
      <div class="container-fluid">
        <!-- شعار المتجر -->
        <a class="navbar-brand" href="#">
          <img src="/images/logo-brand.png" alt="شعار المتجر" class="logo-brand" />
        </a>
        
        <!-- زر القائمة المنسدلة (Toggle Button) -->
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <!-- القائمة -->
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">الرئيسية</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">المنتجات</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">العلامات التجارية</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">التصنيفات</a>
            </li>
          </ul>
        </div>
        
        <!-- شريط التسجيل والبحث -->
        <div class="login-search">
         
          <div class="search-bar">
            <input type="text" placeholder="ابحث عن منتجات..." class="form-control" />
            <button class="btn btn-primary">بحث</button>
          </div>
        </div>
      </div>
    </nav>

    <!-- المحتوى الرئيسي -->
    <div class="main-container">
  
    <!-- قسم العلامات التجارية -->
    <div class="brands-section">
      <div class="container">
        <!-- محتوى قسم العلامات التجارية -->
      </div>
    </div>

    <!-- قسم التصنيفات -->
    <div class="categories-section">
      <div class="container">
        <!-- محتوى قسم التصنيفات -->
      </div>
    </div>
  </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const isDarkMode = ref(false);

const toggleDarkMode = () => {
  isDarkMode.value = !isDarkMode.value;
};
</script>
